### ISSUE TITLE
Rendre le peuplement plus cohérent

### ISSUE THREAD

**Issue by superjeffcplusplus** [ODAncona/bdr_projet#4]
- tous les avis ont les mêmes notes ...
- à voir selon les cas à tester

**Comment by superjeffcplusplus** [comment]
J'ai écrit des procédures pour faciliter les insertions de personnes et de bières. 
Mais cette partie n'est pas une priorité

**Comment by ODAncona** [comment]
@superjeffcplusplus Est-ce que c'est terminé ?

**Comment by heryck237** [comment]
modification des notes effectuées.

**Comment by ODAncona** [comment]
Trouver des cas de figure qu'on va pouvoir tester dans le cas des requêtes (respecte les CI)

Exemple respect des chronologie

**Comment by heryck237** [comment]
Vérifications nécessaires au respect du type d’héritage {complete, disjoint}.
 La date de commande doit être inférieure ou égale la date actuelle.
 Si un utilisateur ajoute une adresse d’envoi, elle doit être différente de l’adresse de facturation
Un brasseur désactivé ne peut pas répondre à un avis de bière.
Ajoute un nouveau type de bière si on tente d'insérer une bière avec un type de bière qui n'existe pas encore.

**Comment by ODAncona** [comment]
La base de donnée est fonctionnelle + cohérente DONE
