### ISSUE TITLE
Rapport

### ISSUE THREAD

**Issue by superjeffcplusplus** [ODAncona/bdr_projet#5]
C'est une des choses les plus importantes !

**Comment by ODAncona** [comment]
Je m'occupe du rapport. Je commence à travailler dessus Jeudi après-midi.

**Comment by ODAncona** [comment]
Done Guide Installation

**Comment by ODAncona** [comment]
Ajouter readme dans manuels

**Comment by ODAncona** [comment]
FINALLY
