### ISSUE TITLE
Page d'accueil

### ISSUE THREAD

**Issue by superjeffcplusplus** [ODAncona/bdr_projet#7]
Pour la page d'accueil, mettre en avant les 'meilleures' bières.
Proposition de critères :

1. Bières qui sont moins chères que la moyenne, qui ont une note moyenne des avis au-dessus de la moyenne des avis et qui ont un nombre de commentaires au-dessus de la moyenne du nombre d'avis par bière.
2. Ensuite faire la même mais avec un critère un moins, puis encore un en moins etc

**Comment by ODAncona** [comment]
vue les plus récentes

**Comment by ODAncona** [comment]
DONE
